import fs from 'node:fs';
import path from 'node:path';

const outPath = path.join(process.cwd(), 'references', 'power_spell_definition_v1_current.json');
const levelProgression = (entries = {}) => {
  const out = {};
  for (let i = 1; i <= 5; i += 1) {
    const raw = entries[i] ?? [];
    const ruleText = Array.isArray(raw) ? raw : [raw];
    out[i] = { enabled: ruleText.length > 0, ruleText };
  }
  return out;
};
const spell = (o) => ({
  id: 'spell_id', name: 'Spell Name', abbreviation: '', parentSpellId: null, spellRole: 'standalone',
  mode: 'active', category: 'utility', summary: '', flavorText: '', unlockLevel: 1, visibleInCombatUI: true,
  combatUI: { showSpellStep: true, showTargetStep: true, showModeStep: false, showStatStep: false, showDamageTypeStep: false, showSummonStep: false, showAttackResolutionStep: false, showAllocationStep: false, contextualActionOnly: false, ...(o.combatUI ?? {}) },
  targeting: { targetMode: 'single', targetCount: 1, targetCountByLevel: {}, validTargetTypes: [], validDispositions: [], canTargetSelf: false, canTargetAllies: false, canTargetEnemies: false, requiresExplicitTargetSelection: true, allowsTargetInclusionExclusion: false, requiresLineOfSight: false, range: { type: 'touch', value: null, unit: 'm', perLevelMultiplier: null, ...(o.targeting?.range ?? {}) }, ...(o.targeting ?? {}) },
  costs: { actionCost: 'standard', manaCost: 0, manaCostByLevel: {}, bonusManaAllowed: false, bonusManaScalingText: '', usageLimits: [], ...(o.costs ?? {}) },
  duration: { type: 'instant', value: null, unit: 'turn', durationByLevel: {}, requiresUpkeep: false, upkeepCost: null, endsOnCasterCancel: false, endsOnCasterLoss: false, ...(o.duration ?? {}) },
  mechanics: { sourceLinked: false, createsAuraSource: false, createsSummon: false, createsKnowledgeCard: false, writesHistoryLink: false, effects: [], statusChanges: [], resourceChanges: [], scalingRulesText: [], specialRulesText: [], implementationNotes: [], ...(o.mechanics ?? {}) },
  levelProgression: o.levelProgression ?? levelProgression(),
  validation: { blockingMissingFields: [], nonBlockingMissingFields: [], warnings: [], openQuestions: [], ...(o.validation ?? {}) },
  ...o,
});
const power = (o) => ({
  definitionStatus: { state: 'reference-example', readyForImplementation: false, blockingMissingFields: [], nonBlockingMissingFields: [], assumptions: [], notes: ['Mapped from current source JSON and runtime modules.', 'Discussion/reference only.'], ...(o.definitionStatus ?? {}) },
  source: { documents: ['json_refs/powers.json'], sourceTextVersion: 'schema_version:5', ingestedAt: '2026-04-05', author: 'Codex', ...(o.source ?? {}) },
  power: { id: 'power_id', name: 'Power Name', abbreviation: '', governingStat: '', theme: '', summary: '', tags: [], combatEnabled: true, supportsPassives: true, supportsActiveSpells: true, notes: [], ...(o.power ?? {}) },
  globalRules: { sharedRulesText: [], sharedConstraints: [], sharedKeywords: [], defaultActionCost: null, defaultManaCost: null, defaultRange: null, defaultDuration: null, ...(o.globalRules ?? {}) },
  spells: o.spells ?? [],
});

const data = {
  schemaVersion: 'power-spell-definition-v1',
  notes: [
    'This file maps the current branch powers and spells into the v1 definition structure.',
    'It is intentionally verbose so the team can judge whether the structure is too decorated.',
    'Unnamed cantrips/passives are flagged in validation warnings.'
  ],
  powerDefinitions: [
    power({
      source: { documents: ['json_refs/powers.json', 'src/powers/awareness.ts'] },
      power: { id: 'awareness', name: 'Awareness', abbreviation: 'AW', governingStat: 'PER', summary: 'Perception-based passive alertness and information gathering.' },
      globalRules: { sharedRulesText: ['Active Awareness spells are bonus action, 0 mana, and instant in source data.'], defaultActionCost: 'bonus', defaultManaCost: 0, defaultRange: 'line_of_sight_or_touch', defaultDuration: 'instant' },
      spells: [
        spell({ id: 'alerted_self', name: 'Alerted Self', abbreviation: 'AS', mode: 'passive', category: 'passive', summary: 'Passive alertness bonus equal to Awareness level.', visibleInCombatUI: false, combatUI: { showSpellStep: false, showTargetStep: false }, targeting: { targetMode: 'self', targetCount: 0, canTargetSelf: true, requiresExplicitTargetSelection: false }, duration: { type: 'passive' }, mechanics: { specialRulesText: ['Alertness bonus equals current Awareness level.'], implementationNotes: ['Implemented by AwarenessPassiveProvider.'] }, levelProgression: levelProgression({ 1: 'Passive alertness bonus begins.', 2: 'Bonus continues scaling by level.', 3: 'Bonus continues scaling by level.', 4: 'Bonus continues scaling by level.', 5: 'Bonus continues scaling by level.' }) }),
        spell({ id: 'awakened_insight', name: 'Awakened Insight', abbreviation: 'AI', mode: 'passive', category: 'passive', summary: 'Temporary inspiration support passive.', visibleInCombatUI: false, combatUI: { showSpellStep: false, showTargetStep: false }, targeting: { targetMode: 'self', targetCount: 0, canTargetSelf: true, requiresExplicitTargetSelection: false }, duration: { type: 'passive' }, mechanics: { specialRulesText: ['Source JSON: 1 temporary inspiration per session, non-stacking, blocked by uninspired.'], implementationNotes: ['Not implemented in current passive provider.'] }, levelProgression: levelProgression({ 1: 'Source-defined from level 1.' }), validation: { warnings: ['Current runtime does not implement Awakened Insight.'] } }),
        spell({ id: 'assess_character', name: 'Assess Character', abbreviation: 'AC', category: 'knowledge', summary: 'Read a target character and record identified information.', visibleInCombatUI: true, combatUI: { showSpellStep: false, showTargetStep: true }, targeting: { targetMode: 'single', validTargetTypes: ['character'], validDispositions: ['ally', 'enemy', 'neutral'], canTargetAllies: true, canTargetEnemies: true, requiresLineOfSight: true, range: { type: 'line_of_sight' } }, costs: { actionCost: 'bonus', manaCost: 0 }, mechanics: { effects: ['LogEffect', 'HistoryEffect'], specialRulesText: ['Current runtime writes a history entry, not a standalone knowledge card.', 'Target CR must not exceed the caster threshold.'] }, levelProgression: levelProgression({ 1: 'Reveals stats and skills. CR limit PER + 1 capped at 6.', 2: 'Adds powers and specials. CR limit PER + 2 capped at 9.', 3: 'CR limit PER + 3 capped at 12. Ignores techno-invisibility devices.', 4: 'CR limit PER + 4 capped at 15.', 5: 'CR limit PER + 5 capped at 18. Source says results may be shared with party members.' }) }),
        spell({ id: 'artifact_appraisal', name: 'Artifact Appraisal', abbreviation: 'AA', category: 'knowledge', summary: 'Identify an item quality band by touch.', visibleInCombatUI: false, combatUI: { showSpellStep: false, showTargetStep: false }, targeting: { targetMode: 'single', validTargetTypes: ['item'], range: { type: 'touch' } }, costs: { actionCost: 'bonus', manaCost: 0 }, mechanics: { specialRulesText: ['Source JSON identifies item quality up to a level-specific maximum.'], implementationNotes: ['Present in source JSON, not wired in current runtime module.'] }, levelProgression: levelProgression({ 1: 'Identifies common/uncommon/masterwork.', 2: 'Identifies rare or lesser.', 3: 'Identifies epic or lesser.', 4: 'Identifies legendary or lesser.', 5: 'Identifies demonic/celestial/mythical or lesser.' }), validation: { warnings: ['Current awarenessModule only exposes assess_character.'] } })
      ]
    }),
    power({
      source: { documents: ['json_refs/powers.json', 'src/powers/bodyReinforcement.ts'] },
      power: { id: 'body_reinforcement', name: 'Body Reinforcement', abbreviation: 'BR', governingStat: 'STAM', summary: 'Physical reinforcement buff plus revive cantrip/passive.' },
      globalRules: { sharedRulesText: ['Main buff spell is standard action with a timed duration.'], defaultActionCost: 'standard', defaultDuration: 'timed' },
      spells: [
        spell({ id: 'default', name: 'Boost Physique', abbreviation: 'BP', category: 'buff', summary: 'Increase STR, DEX, or STAM and later add damage reduction.', combatUI: { showSpellStep: false, showTargetStep: true, showStatStep: true }, targeting: { targetMode: 'single', validTargetTypes: ['character'], validDispositions: ['self', 'ally'], canTargetSelf: true, canTargetAllies: true, range: { type: 'self_or_touch' } }, costs: { actionCost: 'standard', manaCost: 2, manaCostByLevel: { '1': 2, '2': 2, '3': 3, '4': 3, '5': 4 } }, duration: { type: 'timed', durationByLevel: { '1': '10 minutes or 1 portal duration', '2': '10 minutes or 1 portal duration', '3': '10 minutes or 1 portal duration', '4': '30 minutes outside portals or 1 portal duration', '5': '8 hours outside portals or 1 portal duration' } }, mechanics: { effects: ['BuffEffect', 'LogEffect'], specialRulesText: ['Current runtime spell id is still default.', 'User picks one stat from STR / DEX / STAM.'] }, levelProgression: levelProgression({ 1: 'Self target only. +1 to one physical stat.', 2: 'Touch target. Still +1.', 3: '+2 to one physical stat.', 4: '+2 to one physical stat and +1 DR.', 5: '+3 to one physical stat and +2 DR.' }) }),
        spell({ id: 'brute_defiance', name: 'Brute Defiance', abbreviation: 'BD', mode: 'passive', category: 'passive', summary: 'Source cantrip/passive that stands the caster back up after incapacitation.', unlockLevel: 2, visibleInCombatUI: false, combatUI: { showSpellStep: false, showTargetStep: false }, targeting: { targetMode: 'self', targetCount: 0, canTargetSelf: true, requiresExplicitTargetSelection: false }, duration: { type: 'triggered_passive' }, mechanics: { effects: ['ResourceEffect'], resourceChanges: ['currentHp'], specialRulesText: ['Source cantrip trigger is incapacitated, usable once per day.'], implementationNotes: ['Source JSON stores this under cantrip, not as a named level spell.'] }, levelProgression: levelProgression({ 2: 'Stand up with 1 HP after a turn. 1/day.', 5: 'Stand up with 4 HP after a turn. 1/day.' }), validation: { warnings: ['Current runtime module does not expose a dedicated brute_defiance spell id.'] } })
      ]
    }),
    power({
      source: { documents: ['json_refs/powers.json', 'src/powers/crowdControl.ts'] },
      power: { id: 'crowd_control', name: 'Crowd Control', abbreviation: 'CC', governingStat: 'CHA', summary: 'Control contest power with contextual release and passive social bonuses.' },
      globalRules: { sharedRulesText: ['Main control spell costs 0 mana and is maintained over time.', 'Control uses a CHA + INT vs WITS + CHA contest.'], defaultManaCost: 0 },
      spells: [
        spell({ id: 'crowd_management', name: 'Crowd Management', abbreviation: 'CM', mode: 'passive', category: 'passive', summary: 'Passive social skill bonus.', unlockLevel: 2, visibleInCombatUI: false, combatUI: { showSpellStep: false, showTargetStep: false }, targeting: { targetMode: 'self', targetCount: 0, canTargetSelf: true, requiresExplicitTargetSelection: false }, duration: { type: 'passive' }, mechanics: { specialRulesText: ['Current passive provider gives Social + power level.'], implementationNotes: ['Implemented by CrowdControlPassiveProvider.'] }, levelProgression: levelProgression({ 2: 'Social + current Crowd Control level.', 3: 'Social + current Crowd Control level.', 4: 'Social + current Crowd Control level.', 5: 'Social + current Crowd Control level.' }) }),
        spell({ id: 'compulsion_guard', name: 'Compulsion Guard', abbreviation: 'CG', mode: 'passive', category: 'passive', summary: 'Utility trait granted at level 5 by the passive provider.', unlockLevel: 5, visibleInCombatUI: false, combatUI: { showSpellStep: false, showTargetStep: false }, targeting: { targetMode: 'self', targetCount: 0, canTargetSelf: true, requiresExplicitTargetSelection: false }, duration: { type: 'passive' }, mechanics: { specialRulesText: ['Current runtime exposes this as a utility trait only.'] }, levelProgression: levelProgression({ 5: 'Compulsion Guard trait appears at level 5.' }) }),
        spell({ id: 'crowd_control', name: 'Control Entity', abbreviation: 'CE', category: 'control', summary: 'Contest-based paralysis and control effect with upkeep.', combatUI: { showSpellStep: true, showTargetStep: true }, targeting: { targetMode: 'multiple', targetCount: 1, targetCountByLevel: { '1': 1, '2': 1, '3': 2, '4': 2, '5': 3 }, validTargetTypes: ['living', 'non_living_except_other_occult_summons'], validDispositions: ['enemy'], canTargetEnemies: true, range: { type: 'standard', value: 25 } }, costs: { actionCost: 'standard', manaCost: 0 }, duration: { type: 'maintained', requiresUpkeep: true, upkeepCost: '1 mana per turn or per target per turn by level', endsOnCasterCancel: true, endsOnCasterLoss: true }, mechanics: { effects: ['StatusEffect', 'OngoingStateEffect', 'LogEffect'], statusChanges: ['Paralyzed', 'Controlled by caster'], specialRulesText: ['Current runtime checks crowd_control_immunity before allowing the cast.', 'Break rules vary by level and are stored in ongoing state.'] }, levelProgression: levelProgression({ 1: '1 target. Breaks on damage from anyone. Maintain 1 mana/turn.', 2: 'Simple commands allowed with bonus action.', 3: '2 targets. Breaks on caster damage only.', 4: 'Cast becomes bonus action. Commands become free. Damage no longer breaks control.', 5: '3 targets. May target non-living except other occult summons.' }) }),
        spell({ id: 'release_control', name: 'Release Control', abbreviation: 'RC', category: 'control', summary: 'Contextual release action for already controlled targets.', visibleInCombatUI: false, combatUI: { showSpellStep: false, showTargetStep: true, contextualActionOnly: true }, targeting: { targetMode: 'multiple', validTargetTypes: ['controlled_character'], validDispositions: ['enemy'], canTargetEnemies: true, range: { type: 'contextual' } }, costs: { actionCost: 'free', manaCost: 0 }, mechanics: { effects: ['StatusRemovalEffect', 'OngoingStateEffect', 'LogEffect'], statusChanges: ['Remove Paralyzed', 'Remove Controlled by caster'] }, levelProgression: levelProgression({ 1: 'Available as a contextual release for controlled targets.' }), validation: { warnings: ['This is a runtime/contextual action, not a source-defined spell in powers.json.'] } })
      ]
    }),
    power({
      source: { documents: ['json_refs/powers.json', 'src/powers/elementalist.ts'] },
      power: { id: 'elementalist', name: 'Elementalist', abbreviation: '', governingStat: 'INT', summary: 'Direct elemental damage power with a cantrip and split variant.' },
      globalRules: { sharedRulesText: ['Elementalist attack range is standard (25m) in source JSON.'], defaultActionCost: 'standard', defaultRange: '25m' },
      spells: [
        spell({ id: 'elemental_bolt', name: 'Elemental Bolt', abbreviation: 'EB', category: 'attack', summary: 'Main elemental damage spell with damage-type selection and split scaling.', combatUI: { showSpellStep: true, showTargetStep: true, showDamageTypeStep: true }, targeting: { targetMode: 'multiple', targetCount: 1, targetCountByLevel: { '1': 1, '2': 2, '3': 2, '4': 3, '5': 4 }, validTargetTypes: ['character', 'transient_combatant'], validDispositions: ['enemy'], canTargetEnemies: true, range: { type: 'standard', value: 25 } }, costs: { actionCost: 'standard', manaCost: 1, bonusManaAllowed: true, bonusManaScalingText: 'Split bonus rules appear at level 3+ and necrotic cost variant at level 5.' }, mechanics: { effects: ['DamageEffect', 'HealingEffect', 'UsageCounterEffect', 'LogEffect'], specialRulesText: ['Current runtime locks the damage type at low level until long rest.', 'Necrotic can heal undead instead of damaging them.'] }, levelProgression: levelProgression({ 1: 'INT + 1 damage, 1 target, locked element until long rest.', 2: 'INT + 2 damage, split between up to 2 targets.', 3: 'INT + 3 damage, can change elemental type at will.', 4: 'INT + 4 damage, split between up to 3 targets.', 5: 'INT + 5 damage, split between up to 4 targets. Necrotic costs more mana.' }) }),
        spell({ id: 'elemental_cantrip', name: 'Elemental Cantrip', abbreviation: 'EC', category: 'attack', summary: '0-mana elemental damage cantrip.', unlockLevel: 2, combatUI: { showSpellStep: true, showTargetStep: true, showDamageTypeStep: true }, targeting: { targetMode: 'multiple', targetCount: 1, targetCountByLevel: { '2': 1, '4': 1, '5': 2 }, validTargetTypes: ['character', 'transient_combatant'], validDispositions: ['enemy'], canTargetEnemies: true, range: { type: 'standard', value: 25 } }, costs: { actionCost: 'standard', manaCost: 0 }, mechanics: { effects: ['DamageEffect', 'HealingEffect', 'LogEffect'], specialRulesText: ['Source cantrip disallows necrotic damage.'] }, levelProgression: levelProgression({ 2: 'INT damage, 1 target, standard action.', 4: 'INT + 1 damage, bonus action if no other harming spell was cast.', 5: 'INT + 1 damage, may split across 2 targets.' }) }),
        spell({ id: 'elemental_split', name: 'Elemental Split', abbreviation: 'ES', category: 'attack', summary: 'Current runtime explicit split variant.', combatUI: { showSpellStep: true, showTargetStep: true, showDamageTypeStep: true }, targeting: { targetMode: 'multiple', targetCount: 2, validTargetTypes: ['character', 'transient_combatant'], validDispositions: ['enemy'], canTargetEnemies: true, range: { type: 'standard', value: 25 } }, costs: { actionCost: 'standard', manaCost: 1, bonusManaAllowed: true }, mechanics: { effects: ['DamageEffect', 'HealingEffect', 'LogEffect'], specialRulesText: ['This explicit spell exists in runtime even though source JSON folds split into Elemental Bolt.'] }, levelProgression: levelProgression({ 1: 'Runtime exposes a separate split spell id.', 2: 'Runtime exposes a separate split spell id.', 3: 'Runtime exposes a separate split spell id.', 4: 'Runtime exposes a separate split spell id.', 5: 'Runtime exposes a separate split spell id.' }), validation: { warnings: ['elemental_split is a runtime separation; source JSON does not define it as a separate spell.'] } })
      ]
    }),
    power({
      source: { documents: ['json_refs/powers.json', 'src/powers/healing.ts'] },
      power: { id: 'healing', name: 'Healing', abbreviation: '', governingStat: 'INT', summary: 'Restoration power with main healing, purge, and cantrip healing touch.' },
      globalRules: { sharedRulesText: ['Healing uses INT-based restoration in the source JSON.'], defaultActionCost: 'standard' },
      spells: [
        spell({ id: 'heal_living', name: 'Heal Living', abbreviation: 'HL', category: 'restoration', summary: 'Primary healing spell for living targets.', combatUI: { showSpellStep: true, showTargetStep: true, showAllocationStep: true }, targeting: { targetMode: 'multiple', targetCount: 1, targetCountByLevel: { '1': 1, '2': 4, '3': 1, '4': 1, '5': 1 }, validTargetTypes: ['character'], validDispositions: ['self', 'ally'], canTargetSelf: true, canTargetAllies: true, range: { type: 'touch_or_standard', value: 25 } }, costs: { actionCost: 'standard', manaCost: 2, manaCostByLevel: { '1': 2, '2': 2, '3': 3, '4': 3, '5': 3 } }, mechanics: { effects: ['HealingEffect', 'DamageEffect', 'StatusRemovalEffect', 'HistoryEffect', 'UsageCounterEffect', 'LogEffect'], specialRulesText: ['Current runtime converts healing into radiant damage against undead.', 'Overheal and cantrip usage are tracked through usage counters.'] }, levelProgression: levelProgression({ 1: 'INT + 1 healing. Removes bleeding. Touch.', 2: 'INT + 2 healing. Can distribute across up to 4 friendly targets.', 3: 'INT + 3 healing. Source JSON also folds cure effects into the main entry here.', 4: 'INT + 4 healing. Can regrow missing limbs.', 5: 'INT + 5 healing. May overheal up to target STAM once per day.' }) }),
        spell({ id: 'holy_purge', name: 'Holy Purge', abbreviation: 'HP', category: 'restoration', summary: 'Current runtime-separated cleansing spell.', unlockLevel: 3, combatUI: { showSpellStep: true, showTargetStep: true }, targeting: { targetMode: 'single', validTargetTypes: ['character'], validDispositions: ['self', 'ally'], canTargetSelf: true, canTargetAllies: true, range: { type: 'touch_or_standard', value: 25 } }, costs: { actionCost: 'standard', manaCost: 3 }, mechanics: { effects: ['HealingEffect', 'DamageEffect', 'StatusRemovalEffect', 'LogEffect'], specialRulesText: ['Current runtime separates purge logic into its own spell id even though source JSON folds cure into Healing.'] }, levelProgression: levelProgression({ 3: 'Touch-range cleanse of poison, disease, and curse.', 4: 'Range increases to standard (25m).', 5: 'Range remains standard (25m).' }), validation: { warnings: ['holy_purge is a runtime separation; source JSON does not define it as a separate spell name.'] } }),
        spell({ id: 'healing_touch', name: 'Healing Touch', abbreviation: 'HT', category: 'restoration', summary: '0-mana healing cantrip with per-target daily cap.', unlockLevel: 3, combatUI: { showSpellStep: true, showTargetStep: true }, targeting: { targetMode: 'single', validTargetTypes: ['character'], validDispositions: ['self', 'ally'], canTargetSelf: true, canTargetAllies: true, range: { type: 'touch_or_standard', value: 25 } }, costs: { actionCost: 'standard', manaCost: 0, usageLimits: ['2 uses per target per day'] }, mechanics: { effects: ['HealingEffect', 'DamageEffect', 'StatusRemovalEffect', 'UsageCounterEffect', 'LogEffect'] }, levelProgression: levelProgression({ 3: 'Heal 2 HP or stop bleeding. 2 uses per target per day.', 4: 'Heal 3 HP. 2 uses per target per day.', 5: 'Heal 4 HP. 2 uses per target per day.' }) })
      ]
    }),
    power({
      source: { documents: ['json_refs/powers.json', 'src/powers/lightSupport.ts'] },
      power: { id: 'light_support', name: 'Light Support', abbreviation: 'LS', governingStat: 'APP', summary: 'Aura support power with light aura, darkness weakening, mana restoration, and a passive cantrip.' },
      globalRules: { sharedRulesText: ['Core Light Support aura originates from the caster in the source JSON.'], defaultActionCost: 'standard' },
      spells: [
        spell({ id: 'light_support_cantrip', name: 'Light Support Cantrip (unnamed in source)', abbreviation: '', mode: 'passive', category: 'passive', summary: 'Nightvision plus mana bonus cantrip from source JSON.', visibleInCombatUI: false, combatUI: { showSpellStep: false, showTargetStep: false }, targeting: { targetMode: 'self', targetCount: 0, canTargetSelf: true, requiresExplicitTargetSelection: false }, duration: { type: 'passive' }, mechanics: { specialRulesText: ['Nightvision true and mana bonus scales 1 -> 2 -> 3 in source JSON.'], implementationNotes: ['Current lightSupportModule passive provider is empty.'] }, levelProgression: levelProgression({ 1: 'Gain nightvision and +1 mana bonus.', 3: 'Gain nightvision and +2 mana bonus.', 5: 'Gain nightvision and +3 mana bonus.' }), validation: { warnings: ['Source JSON defines this cantrip but gives no formal spell name.', 'Current runtime passive provider does not implement it.'] } }),
        spell({ id: 'let_there_be_light', name: 'Let There Be Light', abbreviation: 'LTBL', category: 'aura', summary: 'Primary light aura source spell.', combatUI: { showSpellStep: true, showTargetStep: true }, targeting: { targetMode: 'single', validTargetTypes: ['character'], validDispositions: ['self', 'ally'], canTargetSelf: true, canTargetAllies: true, range: { type: 'self_aura', value: 50 } }, costs: { actionCost: 'standard', manaCost: 2 }, duration: { type: 'timed_aura', endsOnCasterCancel: true, endsOnCasterLoss: true, durationByLevel: { '1': '10 minutes or 1 portal duration', '2': '30 minutes outside portals or 1 portal duration', '3': '1 hour outside portals or 1 portal duration', '4': '3 hours outside portals or 1 portal duration', '5': '8 hours outside portals or 1 portal duration' } }, mechanics: { sourceLinked: true, createsAuraSource: true, effects: ['AuraEffect', 'LogEffect'], specialRulesText: ['Current runtime auto-shares the aura to friendly participants rather than using explicit include/exclude targeting.'] }, levelProgression: levelProgression({ 1: '+2 attack dice bonus in a 50m aura.', 2: 'Hostiles cannot see the light source. Aura adds +1 DR.', 3: 'Aura becomes +3 attack dice, +1 DR, +1 Soak.', 4: 'Aura radius becomes 100m and bonuses become +3 attack dice, +2 DR, +1 Soak.', 5: 'Aura becomes +4 attack dice, +2 DR, +2 Soak.' }) }),
        spell({ id: 'lessen_darkness', name: 'Lessen Darkness', abbreviation: 'LD', category: 'aura', summary: 'Level 5 linked darkness-weakening aura effect.', unlockLevel: 5, combatUI: { showSpellStep: true, showTargetStep: false }, targeting: { targetMode: 'self', targetCount: 0, canTargetSelf: true, requiresExplicitTargetSelection: false, range: { type: 'linked_to_active_aura' } }, costs: { actionCost: 'standard', manaCost: 0 }, duration: { type: 'linked_aura', endsOnCasterCancel: true, endsOnCasterLoss: true }, mechanics: { sourceLinked: true, effects: ['AuraEffect', 'LogEffect'], specialRulesText: ['Requires an active Let There Be Light source in current runtime.', 'Current runtime applies enemy debuffs automatically.'] }, levelProgression: levelProgression({ 5: 'Reduce darkness-based resistance level by 1 while maintained with the active light source.' }) }),
        spell({ id: 'luminous_restoration', name: 'Luminous Restoration', abbreviation: 'LR', category: 'restoration', summary: 'Restore mana to a target.', unlockLevel: 4, combatUI: { showSpellStep: true, showTargetStep: true }, targeting: { targetMode: 'single', validTargetTypes: ['character'], validDispositions: ['self', 'ally'], canTargetSelf: true, canTargetAllies: true, range: { type: 'standard', value: 25 } }, costs: { actionCost: 'standard', manaCost: 0, usageLimits: ['Source JSON: 1 use per long rest from level 4 onward'] }, mechanics: { effects: ['ManaEffect', 'LogEffect'], resourceChanges: ['currentMana'] }, levelProgression: levelProgression({ 4: 'Restore APP x 2 mana.', 5: 'Current runtime restores APP x 3 mana.' }), validation: { warnings: ['Current runtime unlocks this at level 3; source JSON enables mana_restore at level 4.'] } })
      ]
    }),
    power({
      source: { documents: ['json_refs/powers.json', 'src/powers/necromancy.ts'] },
      power: { id: 'necromancy', name: 'Necromancy', abbreviation: 'NE', governingStat: 'APP', summary: 'Undead summoning, necrotic touch, resurrection, and passive undead affinity.' },
      globalRules: { sharedRulesText: ['Current source folds summon options under one summoning mechanic, while runtime exposes separate summon spell ids.'], defaultActionCost: 'standard' },
      spells: [
        spell({ id: 'necromancy_cantrip', name: 'Necromancy Cantrip (unnamed in source)', abbreviation: '', mode: 'passive', category: 'passive', summary: 'Hostile undead aggro manipulation plus melee bonus.', unlockLevel: 2, visibleInCombatUI: false, combatUI: { showSpellStep: false, showTargetStep: false }, targeting: { targetMode: 'self', targetCount: 0, canTargetSelf: true, requiresExplicitTargetSelection: false }, duration: { type: 'passive' }, mechanics: { specialRulesText: ['Source JSON: hostile undead aggro priority changes and melee bonus scales over the cantrip levels.'], implementationNotes: ['Current necromancyModule passive provider is empty.'] }, levelProgression: levelProgression({ 2: 'Hostile undead aggro priority last; melee +1.', 4: 'Hostile undead aggro priority last; melee +2.', 5: 'Hostile undead ignore unless attacked first; melee +2.' }), validation: { warnings: ['Source JSON defines this cantrip but gives no formal spell name.', 'Current runtime passive provider does not implement it.'] } }),
        spell({ id: 'non_living_skeleton', name: 'Non-Living Skeleton', abbreviation: 'NS', category: 'summon', summary: 'Current runtime explicit skeleton summon option.', combatUI: { showSpellStep: true, showTargetStep: false }, targeting: { targetMode: 'self', targetCount: 0, canTargetSelf: true, requiresExplicitTargetSelection: false, range: { type: 'near_caster' } }, costs: { actionCost: 'standard', manaCost: 2 }, duration: { type: 'timed_summon', endsOnCasterLoss: true }, mechanics: { createsSummon: true, effects: ['SummonEffect', 'AuraEffect', 'LogEffect'], specialRulesText: ['Current runtime inherits aura effects onto summons when relevant.'] }, levelProgression: levelProgression({ 1: 'Summon 1 simple skeleton.', 2: 'Still available as an explicit summon option.', 3: 'Still available as an explicit summon option.', 4: 'Summon duration increases and summon bonuses improve globally.', 5: 'Summon bonuses increase further.' }), validation: { warnings: ['Source JSON models summon choices under a shared summoning mechanic rather than as separate named spells.'] } }),
        spell({ id: 'non_living_skeleton_king', name: 'Non-Living Skeleton King', abbreviation: 'NSK', category: 'summon', summary: 'Current runtime explicit skeleton king summon option.', unlockLevel: 2, combatUI: { showSpellStep: true, showTargetStep: false }, targeting: { targetMode: 'self', targetCount: 0, canTargetSelf: true, requiresExplicitTargetSelection: false, range: { type: 'near_caster' } }, costs: { actionCost: 'standard', manaCost: 3 }, duration: { type: 'timed_summon', endsOnCasterLoss: true }, mechanics: { createsSummon: true, effects: ['SummonEffect', 'AuraEffect', 'LogEffect'] }, levelProgression: levelProgression({ 2: 'May summon 1 skeleton king instead of multiple simple skeletons.', 3: 'Still available.', 4: 'Still available with stronger global summon bonuses.', 5: 'Still available with stronger global summon bonuses.' }), validation: { warnings: ['Source JSON models summon choices under a shared summoning mechanic rather than as separate named spells.'] } }),
        spell({ id: 'non_living_zombie', name: 'Non-Living Zombie', abbreviation: 'NZ', category: 'summon', summary: 'Current runtime explicit zombie summon option.', unlockLevel: 4, combatUI: { showSpellStep: true, showTargetStep: false }, targeting: { targetMode: 'self', targetCount: 0, canTargetSelf: true, requiresExplicitTargetSelection: false, range: { type: 'near_caster' } }, costs: { actionCost: 'standard', manaCost: 4 }, duration: { type: 'timed_summon', endsOnCasterLoss: true }, mechanics: { createsSummon: true, effects: ['SummonEffect', 'AuraEffect', 'LogEffect'] }, levelProgression: levelProgression({ 4: 'Zombie summon option unlocks.', 5: 'Zombie remains available with stronger global summon bonuses.' }), validation: { warnings: ['Source JSON models summon choices under a shared summoning mechanic rather than as separate named spells.'] } }),
        spell({ id: 'necrotic_touch', name: 'Necrotic Touch', abbreviation: 'NT', category: 'attack', summary: 'Necrotic attack that heals the caster and can heal undead.', unlockLevel: 3, combatUI: { showSpellStep: true, showTargetStep: true, showAttackResolutionStep: true }, targeting: { targetMode: 'single', validTargetTypes: ['character'], validDispositions: ['enemy'], canTargetEnemies: true, range: { type: 'standard', value: 25 } }, costs: { actionCost: 'standard', manaCost: 3 }, mechanics: { effects: ['DamageEffect', 'HealingEffect', 'LogEffect'], specialRulesText: ['Current runtime requires attackOutcome resolution first.', 'Shadow and incorporeal targets are blocked.'] }, levelProgression: levelProgression({ 3: 'APP + Necromancy level necrotic damage. Living targets take 1.5x. Caster heals by power level.', 4: 'Same damage profile.', 5: 'APP + 2 x Necromancy level damage. Caster still heals by power level.' }) }),
        spell({ id: 'necromancers_bless', name: "Necromancer's Bless", abbreviation: 'NB', category: 'restoration', summary: 'Current runtime resurrection spell.', unlockLevel: 5, combatUI: { showSpellStep: true, showTargetStep: true }, targeting: { targetMode: 'single', validTargetTypes: ['character'], validDispositions: ['ally', 'neutral'], canTargetAllies: true, range: { type: 'touch_or_recent_dead' } }, costs: { actionCost: 'standard', manaCost: 6 }, mechanics: { effects: ['ResourceEffect', 'StatusRemovalEffect', 'LogEffect'], resourceChanges: ['currentHp'], specialRulesText: ['Current runtime sets HP to 1 and removes bleeding/dead/dying/unconscious.'] }, levelProgression: levelProgression({ 5: 'Resurrect a recently fallen target within the source resurrection window.' }) })
      ]
    }),
    power({
      source: { documents: ['json_refs/powers.json', 'src/powers/shadowControl.ts'] },
      power: { id: 'shadow_control', name: 'Shadow Control', abbreviation: 'SC', governingStat: 'MAN', summary: 'Shadow cloak, movement, damage, summon, and cosmetic cantrip power.' },
      globalRules: { sharedRulesText: ['Shadow Walk range scales by 25 meters x Shadow Control level in source JSON.'] },
      spells: [
        spell({ id: 'shadow_control_cantrip', name: 'Shadow Control Cantrip (unnamed in source)', abbreviation: '', mode: 'passive', category: 'passive', summary: 'Cosmetic changes to clothing/armor and later minor body cosmetics.', unlockLevel: 3, visibleInCombatUI: false, combatUI: { showSpellStep: false, showTargetStep: false }, targeting: { targetMode: 'self', targetCount: 0, canTargetSelf: true, requiresExplicitTargetSelection: false }, duration: { type: 'passive' }, mechanics: { specialRulesText: ['Purely cosmetic according to the source JSON.'], implementationNotes: ['Current shadowControlModule passive provider is empty.'] }, levelProgression: levelProgression({ 3: 'Cosmetic changes on clothes or armor.', 5: 'Also allows minor cosmetic appearance modifications on the body.' }), validation: { warnings: ['Source JSON defines this cantrip but gives no formal spell name.', 'Current runtime passive provider does not implement it.'] } }),
        spell({ id: 'smoldering_shadow', name: 'Smoldering Shadow', abbreviation: 'SS', category: 'aura', summary: 'Shadow cloak buff with optional ally sharing at higher levels.', combatUI: { showSpellStep: true, showTargetStep: true, showModeStep: true }, targeting: { targetMode: 'single', validTargetTypes: ['character'], validDispositions: ['self', 'ally'], canTargetSelf: true, canTargetAllies: true, range: { type: 'self_or_shared', value: 25 } }, costs: { actionCost: 'standard', manaCost: 2, manaCostByLevel: { '1': 2, '2': 2, '3': 2, '4': 2, '5': 4 } }, duration: { type: 'timed_aura', endsOnCasterCancel: true, endsOnCasterLoss: true, durationByLevel: { '1': '10 minutes outside portals or 1 portal duration', '2': '10 minutes outside portals or 1 portal duration', '3': '10 minutes outside portals or 1 portal duration', '4': '60 minutes outside portals or 1 portal duration', '5': '60 minutes outside portals or 1 portal duration' } }, mechanics: { sourceLinked: true, createsAuraSource: true, effects: ['AuraEffect', 'LogEffect'], specialRulesText: ['Current runtime uses castMode self vs aura.', 'Current runtime auto-selects friendly recipients in aura mode instead of explicit include/exclude targeting.'] }, levelProgression: levelProgression({ 1: 'Stealth +1, Intimidation +1, AC +1.', 2: 'Stealth +2, Intimidation +2, AC +1. Shadow Walk unlocks.', 3: 'Stealth +3, Intimidation +3, AC +2. Shadow Manipulation unlocks.', 4: 'Stealth +4, Intimidation +4, AC +2. May be shared with allies.', 5: 'Stealth +5, Intimidation +5, AC +3. Shared mode costs more mana.' }) }),
        spell({ id: 'shadow_walk', name: 'Shadow Walk', abbreviation: 'SW', category: 'utility', summary: 'Move through shadows to a living target shadow.', unlockLevel: 2, combatUI: { showSpellStep: true, showTargetStep: true }, targeting: { targetMode: 'single', validTargetTypes: ['living_character'], validDispositions: ['ally', 'enemy', 'neutral'], canTargetAllies: true, canTargetEnemies: true, range: { type: 'per_level', perLevelMultiplier: 25, unit: 'm' } }, costs: { actionCost: 'bonus', manaCost: 2 }, mechanics: { effects: ['LogEffect'] }, levelProgression: levelProgression({ 2: 'Range 50m.', 3: 'Range 75m.', 4: 'Range 100m.', 5: 'Range 125m.' }) }),
        spell({ id: 'shadow_walk_attack', name: 'Shadow Walk and Attack', abbreviation: 'SWaA', category: 'utility', summary: 'Current runtime ambush action logged as a separate utility spell.', unlockLevel: 2, combatUI: { showSpellStep: true, showTargetStep: true }, targeting: { targetMode: 'single', validTargetTypes: ['living_character'], validDispositions: ['enemy'], canTargetEnemies: true, range: { type: 'per_level', perLevelMultiplier: 25, unit: 'm' } }, costs: { actionCost: 'bonus_plus_standard', manaCost: 2 }, mechanics: { effects: ['LogEffect'], specialRulesText: ['Current runtime logs the ambush but does not auto-resolve the follow-up attack in this action.'] }, levelProgression: levelProgression({ 2: 'Ambush through shadow at 50m.', 3: 'Ambush through shadow at 75m.', 4: 'Ambush through shadow at 100m.', 5: 'Ambush through shadow at 125m.' }) }),
        spell({ id: 'shadow_manipulation', name: 'Shadow Manipulation', abbreviation: 'SM', category: 'attack', summary: 'Use a target own shadow to attack them.', unlockLevel: 3, combatUI: { showSpellStep: true, showTargetStep: true }, targeting: { targetMode: 'single', validTargetTypes: ['character'], validDispositions: ['enemy'], canTargetEnemies: true, range: { type: 'standard', value: 25 } }, costs: { actionCost: 'standard', manaCost: 2 }, mechanics: { effects: ['DamageEffect', 'LogEffect'], specialRulesText: ['Source JSON marks this as auto-hit with shadow damage soakable by STAM.'] }, levelProgression: levelProgression({ 3: 'MAN + SC level shadow damage.', 4: 'Same damage formula.', 5: 'Same damage formula.' }) }),
        spell({ id: 'shadow_fighter', name: 'Shadow Fighter', abbreviation: 'SF', category: 'summon', summary: 'Summon a shadow soldier/fighter.', unlockLevel: 5, combatUI: { showSpellStep: true, showTargetStep: false }, targeting: { targetMode: 'self', targetCount: 0, canTargetSelf: true, requiresExplicitTargetSelection: false, range: { type: 'near_caster' } }, costs: { actionCost: 'standard', manaCost: 4 }, duration: { type: 'timed_summon', endsOnCasterLoss: true }, mechanics: { createsSummon: true, effects: ['SummonEffect', 'AuraEffect', 'LogEffect'] }, levelProgression: levelProgression({ 5: 'Summon 1 shadow fighter at 4 mana.' }) })
      ]
    })
  ]
};
fs.writeFileSync(outPath, JSON.stringify(data, null, 2) + '\n', 'utf8');
console.log(`Wrote ${outPath}`);
